x-app: &app
  build: .

services:
  node1:
    <<: *app
    environment:
      - RAFT_ADDRESS=node1:9292
  node2:
    <<: *app
    environment:
      - RAFT_ADDRESS=node2:9292
  node3:
    <<: *app
    environment:
      - RAFT_ADDRESS=node3:9292
