x-app: &app
  build: .
  restart: unless-stopped

services:
  node1:
    <<: *app
    environment:
      - RAFT_ADDRESS=node1:2773
    ports:
      - "8080:8080"
  node2:
    <<: *app
    environment:
      - RAFT_ADDRESS=node2:2773
      - RAFT_LEADER_API=http://node1:8080
    ports:
      - "8081:8080"
  node3:
    <<: *app
    environment:
      - RAFT_ADDRESS=node3:2773
      - RAFT_LEADER_API=http://node1:8080
    ports:
      - "8082:8080"
